name: osmos
description: A diabetes management application
publish_to: 'none'

environment:
  sdk: '^3.7.0'

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^7.0.1
  flutter_facebook_auth: ^7.1.2
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.4.0
  country_picker: ^2.0.27
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  lottie: ^2.5.0
  shared_preferences: ^2.5.3
  provider: ^6.1.4
  cloud_firestore: ^5.6.6
  intl: ^0.20.2
  firebase_core_platform_interface: ^5.4.0
  speech_to_text: ^6.6.0
  flutter_tts: ^3.8.5
  avatar_glow: 2.0.0
  chat_gpt_sdk: ^3.0.0
  oauth2_client: ^3.2.1
  http: ^1.4.0
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  geocoding: ^2.1.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  flutter_local_notifications: ^16.3.2
  fl_chart: ^0.66.2
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.6

flutter:
  uses-material-design: true
  assets:
      #- assets/lottie/health_hero.json
      - assets/images/osmoslogo.png
  fonts:
    - family: League Spartan
      fonts:
        - asset: assets/fonts/LeagueSpartan-Regular.ttf
        - asset: assets/fonts/LeagueSpartan-Medium.ttf
          weight: 500
        - asset: assets/fonts/LeagueSpartan-Light.ttf
          weight: 300